[package]
name = "speech-to-text-chatgpt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pv_cheetah = "*"
hound = "3.5.0"
rodio = "0.17.1"
dotenv = "0.15.0"
